name: budgetor
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.8.1
  timezone: ^0.9.4
  path_provider: ^2.1.4
  flutter_local_notifications: ^18.0.1
  unity_ads_plugin: ^0.3.22
  path: ^1.9.0
  internet_connection_checker_plus: ^2.5.2
  in_app_review: ^2.0.10
  in_app_update: ^4.2.3
  tutorial_coach_mark: ^1.2.12
  line_icons: ^2.0.3
  flutter_timezone: ^4.0.0
  firebase_analytics: ^11.3.6
  device_info_plus: ^11.1.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_screenutil: ^5.9.3
  firebase_messaging: ^15.1.6
  intl: ^0.20.1
  flutter_vector_icons: ^2.0.0
  uuid: ^4.5.1
  purchases_flutter: ^8.3.0
  package_info_plus: ^8.1.1
  loading_overlay: ^0.4.2
  url_launcher: ^6.3.1
  nb_utils: ^7.0.7
  flutter_riverpod: ^2.6.1
  flex_color_scheme: ^8.0.2
  flutter_animate: ^4.5.2
  firebase_crashlytics: ^4.2.0
  share_plus: ^10.1.2
  logger: ^2.5.0
  introduction_screen: ^3.1.14
  flutter_email_sender: ^6.0.3
  lottie: ^3.1.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  sign_in_button: ^3.2.0
  workmanager: ^0.5.2

dev_dependencies:
  # flutter_native_splash: ^2.3.10
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true




  assets:
    - assets/
    - assets/anims/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    - family: Madimi
      fonts:
        - asset: assets/fonts/MadimiOne-Regular.ttf

# native_splash
# dart run flutter_native_splash:create
flutter_native_splash:
  color: '#03346E'
  color_dark: '#201E43'
  android_12:
    color: '#03346E'
    color_dark: '#201E43'
